// Tests for scripts/lint/check-managed-blocks.mjs. Each test stands up a
// scratch git repo in a temp dir, writes markdown into it, runs the linter as a
// subprocess, and asserts on exit code + emitted output.
//
// The linter reads its file list from `git ls-files`, so every fixture has to be
// staged -- an unstaged file is invisible to it, same as in a real checkout.

import assert from 'node:assert/strict';
import { execFileSync, spawnSync } from 'node:child_process';
import { mkdirSync, mkdtempSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { describe, it } from 'node:test';
import { fileURLToPath } from 'node:url';

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(HERE, '..', '..');
const LINTER = join(REPO_ROOT, 'scripts', 'lint', 'check-managed-blocks.mjs');

const RULES = 'MD012 MD024 MD034';
const DISABLE = `<!-- markdownlint-disable ${RULES} -->`;
const ENABLE = `<!-- markdownlint-enable ${RULES} -->`;

function scaffold() {
  const root = mkdtempSync(join(tmpdir(), 'check-blocks-'));
  execFileSync('git', ['init', '-q'], { cwd: root });
  execFileSync('git', ['config', 'user.email', 'test@example.com'], { cwd: root });
  execFileSync('git', ['config', 'user.name', 'test'], { cwd: root });
  return root;
}

function writeFile(root, relPath, text) {
  const p = join(root, relPath);
  mkdirSync(dirname(p), { recursive: true });
  writeFileSync(p, text);
}

function run(root) {
  execFileSync('git', ['add', '-A'], { cwd: root });
  const r = spawnSync('node', [LINTER, '--root', root], { encoding: 'utf8' });
  return { code: r.status, stdout: r.stdout, stderr: r.stderr };
}

// A correctly fenced managed block, the shape this linter exists to enforce.
function fencedBlock(name, body) {
  return [DISABLE, `<!-- BEGIN ${name} -->`, body, `<!-- END ${name} -->`, ENABLE].join('\n');
}

describe('check-managed-blocks', () => {
  it('passes on a repo with no markdown at all', () => {
    const root = scaffold();
    writeFile(root, 'README.txt', 'not markdown\n');
    const r = run(root);
    assert.equal(r.code, 0, r.stderr);
    assert.match(r.stdout, /0 managed block\(s\)/);
  });

  it('passes on markdown with no managed blocks', () => {
    const root = scaffold();
    writeFile(root, 'doc.md', '# Doc\n\n<!-- an ordinary comment -->\n\nBody.\n');
    const r = run(root);
    assert.equal(r.code, 0, r.stderr);
  });

  it('passes on a correctly fenced managed block', () => {
    const root = scaffold();
    writeFile(root, 'AGENTS.md', `# Doc\n\n${fencedBlock('BEADS INTEGRATION v:1', 'See https://example.com/x')}\n`);
    const r = run(root);
    assert.equal(r.code, 0, r.stderr);
    assert.match(r.stdout, /1 managed block\(s\) in 1 file\(s\)/);
  });

  it('counts multiple fenced blocks in one file', () => {
    const root = scaffold();
    const body = [
      '# Doc',
      '',
      fencedBlock('BEADS INTEGRATION', 'a'),
      '',
      fencedBlock('BEADS CODEX SETUP: generated by bd setup codex', 'b'),
      '',
    ].join('\n');
    writeFile(root, 'AGENTS.md', body);
    const r = run(root);
    assert.equal(r.code, 0, r.stderr);
    assert.match(r.stdout, /2 managed block\(s\)/);
  });

  it('fails when a managed block has no fence -- the ecosystem-55g regression', () => {
    const root = scaffold();
    writeFile(root, 'AGENTS.md', '# Doc\n\n<!-- BEGIN BEADS INTEGRATION -->\nx\n<!-- END BEADS INTEGRATION -->\n');
    const r = run(root);
    assert.equal(r.code, 1);
    assert.match(r.stderr, /AGENTS\.md:3: managed block is not fenced/);
    assert.match(r.stderr, /AGENTS\.md:5: managed block is not closed/);
  });

  it('fails when the fence omits a required rule', () => {
    const root = scaffold();
    const body = [
      '# Doc',
      '',
      '<!-- markdownlint-disable MD024 -->',
      '<!-- BEGIN BEADS CODEX SETUP -->',
      'See https://example.com/y',
      '<!-- END BEADS CODEX SETUP -->',
      '<!-- markdownlint-enable MD024 -->',
      '',
    ].join('\n');
    writeFile(root, 'CLAUDE.md', body);
    const r = run(root);
    assert.equal(r.code, 1);
    assert.match(r.stderr, /markdownlint-disable above this block omits MD012, MD034/);
    assert.match(r.stderr, /markdownlint-enable below this block omits MD012, MD034/);
  });

  it('fails when only the opening half of the fence is present', () => {
    const root = scaffold();
    writeFile(root, 'CLAUDE.md', `# Doc\n\n${DISABLE}\n<!-- BEGIN X -->\nx\n<!-- END X -->\n`);
    const r = run(root);
    assert.equal(r.code, 1);
    assert.match(r.stderr, /managed block is not closed/);
    assert.doesNotMatch(r.stderr, /is not fenced/);
  });

  it('reports an unterminated block once, without cascading fence errors', () => {
    const root = scaffold();
    writeFile(root, 'doc.md', `# Doc\n\n${DISABLE}\n<!-- BEGIN THING -->\nbody with no end\n`);
    const r = run(root);
    assert.equal(r.code, 1);
    assert.match(r.stderr, /doc\.md:4: managed block "<!-- BEGIN THING -->" has no matching/);
    assert.match(r.stderr, /1 error\(s\)/);
  });

  it('skips files listed in .markdownlintignore', () => {
    const root = scaffold();
    writeFile(root, '.markdownlintignore', 'node_modules/\n**/CHANGELOG.md\n');
    // Generated by release-please and never hand-authored, so an unfenced
    // block inside it is not ours to fix.
    writeFile(root, 'CHANGELOG.md', '<!-- BEGIN GENERATED -->\nx\n<!-- END GENERATED -->\n');
    writeFile(root, 'packages/a/CHANGELOG.md', '<!-- BEGIN GENERATED -->\nx\n<!-- END GENERATED -->\n');
    const r = run(root);
    assert.equal(r.code, 0, r.stderr);
    assert.match(r.stdout, /0 managed block\(s\)/);
  });

  it('still checks non-ignored files when an ignore file is present', () => {
    const root = scaffold();
    writeFile(root, '.markdownlintignore', '**/CHANGELOG.md\n');
    writeFile(root, 'CHANGELOG.md', '<!-- BEGIN GENERATED -->\nx\n<!-- END GENERATED -->\n');
    writeFile(root, 'AGENTS.md', '<!-- BEGIN BEADS INTEGRATION -->\nx\n<!-- END BEADS INTEGRATION -->\n');
    const r = run(root);
    assert.equal(r.code, 1);
    assert.match(r.stderr, /AGENTS\.md:1: managed block is not fenced/);
    assert.doesNotMatch(r.stderr, /CHANGELOG/);
  });

  it('accepts a fence that disables more rules than required', () => {
    const root = scaffold();
    const body = [
      '# Doc',
      '',
      '<!-- markdownlint-disable MD012 MD024 MD034 MD041 -->',
      '<!-- BEGIN X -->',
      'x',
      '<!-- END X -->',
      '<!-- markdownlint-enable MD012 MD024 MD034 MD041 -->',
      '',
    ].join('\n');
    writeFile(root, 'doc.md', body);
    const r = run(root);
    assert.equal(r.code, 0, r.stderr);
  });

  it('checks the real repository', () => {
    const r = spawnSync('node', [LINTER, '--root', REPO_ROOT], { encoding: 'utf8' });
    assert.equal(r.status, 0, r.stderr);
  });
});
