#!/usr/bin/env bash
# Brief orchestrator for Counsel.
#
# Checks whether a fresh brief is needed, runs the full synthesis pipeline,
# writes a Markdown brief to ~/.onlooker/counsel/<project-key>/briefs/,
# and emits counsel.brief.generated.
#
# Exposes:
#   counsel_brief_is_stale <project_key> <interval_days>
#     Returns 0 if a new brief should be generated, 1 if the existing one is fresh.
#
#   counsel_generate_brief <session_id> <cwd>
#     Runs the full pipeline. Echoes the output path on success.
#     Returns 2 if skipped (not stale or too few events).
#     Returns 1 on hard failure.

# shellcheck source=./counsel-reader.sh
# shellcheck source=./counsel-synthesize.sh
# shellcheck source=./counsel-events.sh
# shellcheck source=./counsel-project-key.sh
# (caller must source these before counsel-brief.sh)

_counsel_latest_brief_path() {
	local briefs_dir="${1:-}"
	[[ -d "$briefs_dir" ]] || return 1
	# Briefs are named YYYY-WW.md; newest sorts last lexicographically.
	local latest
	latest=$(ls -1 "$briefs_dir"/*.md 2>/dev/null | sort | tail -1)
	[[ -n "$latest" ]] || return 1
	printf '%s' "$latest"
}

_counsel_brief_mtime_epoch() {
	local path="${1:-}"
	[[ -f "$path" ]] || { printf '0'; return 0; }
	if [[ "$(uname)" == "Darwin" ]]; then
		stat -f '%m' "$path" 2>/dev/null || printf '0'
	else
		stat -c '%Y' "$path" 2>/dev/null || printf '0'
	fi
}

counsel_brief_is_stale() {
	local project_key="${1:-}"
	local interval_days="${2:-7}"

	local briefs_dir
	briefs_dir=$(counsel_project_dir "$project_key")

	local latest_path
	latest_path=$(_counsel_latest_brief_path "$briefs_dir") || { return 0; }

	local mtime now age_days
	mtime=$(_counsel_brief_mtime_epoch "$latest_path")
	now=$(date +%s 2>/dev/null) || now=0
	age_days=$(( (now - mtime) / 86400 ))

	[[ "$age_days" -ge "$interval_days" ]]
}

_counsel_format_brief() {
	local brief_json="${1:-}"
	local period_start="${2:-}"
	local period_end="${3:-}"
	local event_count="${4:-0}"

	local summary patterns_json recs_json wins_json watch_json
	summary=$(printf '%s' "$brief_json" | jq -r '.summary // ""' 2>/dev/null) || summary=""
	patterns_json=$(printf '%s' "$brief_json" | jq -c '.patterns // []' 2>/dev/null) || patterns_json="[]"
	recs_json=$(printf '%s' "$brief_json" | jq -c '.recommendations // []' 2>/dev/null) || recs_json="[]"
	wins_json=$(printf '%s' "$brief_json" | jq -c '.wins // []' 2>/dev/null) || wins_json="[]"
	watch_json=$(printf '%s' "$brief_json" | jq -c '.watch // []' 2>/dev/null) || watch_json="[]"

	local timestamp
	timestamp=$(date '+%Y-%m-%dT%H:%M:%SZ' 2>/dev/null) || timestamp="unknown"

	{
		printf '# Counsel Brief: %s — %s\n\n' "$period_start" "$period_end"
		[[ -n "$summary" ]] && printf '> %s\n\n' "$summary"

		printf '## Recommendations\n\n'
		local rec_count
		rec_count=$(printf '%s' "$recs_json" | jq 'length' 2>/dev/null) || rec_count=0
		if [[ "$rec_count" -gt 0 ]]; then
			local i
			for ((i = 0; i < rec_count; i++)); do
				local title rationale priority
				title=$(printf '%s' "$recs_json" | jq -r ".[$i].title // \"\"" 2>/dev/null) || title=""
				rationale=$(printf '%s' "$recs_json" | jq -r ".[$i].rationale // \"\"" 2>/dev/null) || rationale=""
				priority=$(printf '%s' "$recs_json" | jq -r ".[$i].priority // \"medium\"" 2>/dev/null) || priority="medium"
				[[ -z "$title" ]] && continue
				printf '### [%s] %s\n\n' "$priority" "$title"
				[[ -n "$rationale" ]] && printf '%s\n\n' "$rationale"
			done
		else
			printf '*No recommendations this period.*\n\n'
		fi

		printf '## Patterns Observed\n\n'
		local pat_count
		pat_count=$(printf '%s' "$patterns_json" | jq 'length' 2>/dev/null) || pat_count=0
		if [[ "$pat_count" -gt 0 ]]; then
			printf '%s' "$patterns_json" | jq -r '.[]' 2>/dev/null | while IFS= read -r item; do
				[[ -n "$item" ]] && printf '- %s\n' "$item"
			done
			printf '\n'
		else
			printf '*None identified.*\n\n'
		fi

		printf '## Wins\n\n'
		local win_count
		win_count=$(printf '%s' "$wins_json" | jq 'length' 2>/dev/null) || win_count=0
		if [[ "$win_count" -gt 0 ]]; then
			printf '%s' "$wins_json" | jq -r '.[]' 2>/dev/null | while IFS= read -r item; do
				[[ -n "$item" ]] && printf '- %s\n' "$item"
			done
			printf '\n'
		else
			printf '*None noted.*\n\n'
		fi

		printf '## Watch\n\n'
		local watch_count
		watch_count=$(printf '%s' "$watch_json" | jq 'length' 2>/dev/null) || watch_count=0
		if [[ "$watch_count" -gt 0 ]]; then
			printf '%s' "$watch_json" | jq -r '.[]' 2>/dev/null | while IFS= read -r item; do
				[[ -n "$item" ]] && printf '- %s\n' "$item"
			done
			printf '\n'
		else
			printf '*Nothing flagged.*\n\n'
		fi

		printf '---\n'
		printf '*Generated by counsel · %s · %d events analyzed*\n' "$timestamp" "$event_count"
	}
}

counsel_generate_brief() {
	local session_id="${1:-}"
	local cwd="${2:-}"

	[[ -z "$session_id" ]] && return 1

	local onlooker_dir="${ONLOOKER_DIR:-${HOME}/.onlooker}"

	# Resolve config values.
	local interval_days lookback_days model timeout_s max_tokens temperature chars_max min_events
	interval_days=$(counsel_config_get '.counsel.synthesis_interval_days')
	[[ -z "$interval_days" || "$interval_days" == "null" ]] && interval_days="7"
	lookback_days=$(counsel_config_get '.counsel.lookback_days')
	[[ -z "$lookback_days" || "$lookback_days" == "null" ]] && lookback_days="30"
	model=$(counsel_config_get '.counsel.evaluator.model')
	[[ -z "$model" || "$model" == "null" ]] && model="claude-haiku-4-5-20251001"
	timeout_s=$(counsel_config_get '.counsel.evaluator.timeout')
	[[ -z "$timeout_s" || "$timeout_s" == "null" ]] && timeout_s="90"
	max_tokens=$(counsel_config_get '.counsel.evaluator.max_tokens')
	[[ -z "$max_tokens" || "$max_tokens" == "null" ]] && max_tokens="4096"
	temperature=$(counsel_config_get '.counsel.evaluator.temperature')
	[[ -z "$temperature" || "$temperature" == "null" ]] && temperature="0.4"
	chars_max=$(counsel_config_get '.counsel.capture.events_chars_max')
	[[ -z "$chars_max" || "$chars_max" == "null" ]] && chars_max="60000"
	min_events=$(counsel_config_get '.counsel.capture.min_events')
	[[ -z "$min_events" || "$min_events" == "null" ]] && min_events="10"

	local project_key
	project_key=$(counsel_project_key "$cwd")

	# Stale check.
	if ! counsel_brief_is_stale "$project_key" "$interval_days"; then
		return 2
	fi

	# Read events.
	local events_text
	events_text=$(counsel_read_events "$lookback_days" "$chars_max")

	local event_count
	event_count=$(counsel_count_events "$events_text")

	if [[ "$event_count" -lt "$min_events" ]]; then
		return 2
	fi

	# Run synthesis.
	local brief_json
	brief_json=$(counsel_synthesize "$events_text" "$model" "$timeout_s" "$max_tokens" "$temperature") || {
		printf 'counsel_generate_brief: synthesis failed for session %s\n' "$session_id" >&2
		return 1
	}

	# Compute period bounds.
	local now_epoch
	now_epoch=$(date +%s 2>/dev/null) || now_epoch=0
	local period_start period_end
	period_end=$(date '+%Y-%m-%d' 2>/dev/null) || period_end="unknown"
	if [[ "$(uname)" == "Darwin" ]]; then
		period_start=$(date -v "-${lookback_days}d" '+%Y-%m-%d' 2>/dev/null) || period_start="unknown"
	else
		period_start=$(date -d "-${lookback_days} days" '+%Y-%m-%d' 2>/dev/null) || period_start="unknown"
	fi

	# Determine sources consulted.
	local sources_json
	sources_json=$(counsel_sources_from_events "$events_text")

	# Write brief.
	local briefs_dir output_path
	if [[ -n "$project_key" ]]; then
		briefs_dir=$(counsel_project_dir "$project_key")
	else
		briefs_dir="${onlooker_dir}/counsel/unknown/briefs"
	fi

	mkdir -p "$briefs_dir" 2>/dev/null || {
		printf 'counsel_generate_brief: cannot create briefs dir %s\n' "$briefs_dir" >&2
		return 1
	}

	local week_label
	week_label=$(date '+%G-%V' 2>/dev/null) || week_label=$(date '+%Y-%U' 2>/dev/null) || week_label="unknown"
	local filename="${week_label}.md"
	output_path="${briefs_dir}/${filename}"

	local doc
	doc=$(_counsel_format_brief "$brief_json" "$period_start" "$period_end" "$event_count")

	printf '%s\n' "$doc" > "$output_path" 2>/dev/null || {
		printf 'counsel_generate_brief: failed to write %s\n' "$output_path" >&2
		return 1
	}

	# Emit counsel.brief.generated.
	local rec_count
	rec_count=$(printf '%s' "$brief_json" | jq '.recommendations | length' 2>/dev/null) || rec_count=0

	local payload
	payload=$(jq -n \
		--arg ps "$period_start" \
		--arg pe "$period_end" \
		--argjson rc "$rec_count" \
		--argjson src "$sources_json" \
		'{period_start: $ps, period_end: $pe, recommendation_count: $rc, sources_consulted: $src}') || payload=""

	[[ -n "$payload" ]] && counsel_emit_event "counsel.brief.generated" "$payload" || true

	printf '%s' "$output_path"
}
