#!/usr/bin/env bash
# Distillation pipeline for Scribe.
#
# Orchestrates the full Stop-time flow:
#   1. Load session state (captured initial prompt)
#   2. Count transcript turns — skip if below min_turns
#   3. Call scribe_extract_intent (Haiku pass)
#   4. Format output as a readable Markdown document
#   5. Write to ~/.onlooker/scribe/<project_key>/
#   6. Optionally mirror to <repo_root>/<project_dir>/
#   7. Emit scribe.distill.complete
#
# Exposes:
#   scribe_distill <session_id> <cwd> <transcript_path>

# shellcheck source=./scribe-extract.sh
# (caller must source scribe-extract.sh before scribe-distill.sh)

_scribe_format_document() {
	local intent_json="${1:-}"
	local session_id="${2:-unknown}"
	local project_root="${3:-}"
	local captured_prompt="${4:-}"
	local date_str
	date_str=$(date '+%Y-%m-%d' 2>/dev/null) || date_str="unknown"
	local timestamp
	timestamp=$(date '+%Y-%m-%dT%H:%M:%SZ' 2>/dev/null) || timestamp="unknown"

	local summary problem decisions_json tradeoffs_json constraints_json out_of_scope_json
	summary=$(printf '%s' "$intent_json" | jq -r '.summary // ""' 2>/dev/null) || summary=""
	problem=$(printf '%s' "$intent_json" | jq -r '.problem // ""' 2>/dev/null) || problem=""
	decisions_json=$(printf '%s' "$intent_json" | jq -c '.decisions // []' 2>/dev/null) || decisions_json="[]"
	tradeoffs_json=$(printf '%s' "$intent_json" | jq -c '.tradeoffs // []' 2>/dev/null) || tradeoffs_json="[]"
	constraints_json=$(printf '%s' "$intent_json" | jq -c '.constraints // []' 2>/dev/null) || constraints_json="[]"
	out_of_scope_json=$(printf '%s' "$intent_json" | jq -c '.out_of_scope // []' 2>/dev/null) || out_of_scope_json="[]"

	local session_short="${session_id:0:8}"

	{
		printf '# Session Intent: %s\n\n' "$date_str"
		[[ -n "$summary" ]] && printf '> %s\n\n' "$summary"

		printf '## Problem\n\n'
		if [[ -n "$problem" ]]; then
			printf '%s\n\n' "$problem"
		else
			printf '*No problem statement extracted.*\n\n'
		fi

		printf '## Decisions\n\n'
		local decision_count
		decision_count=$(printf '%s' "$decisions_json" | jq 'length' 2>/dev/null) || decision_count=0
		if [[ "$decision_count" -gt 0 ]]; then
			local i
			for ((i = 0; i < decision_count; i++)); do
				local d r alts
				d=$(printf '%s' "$decisions_json" | jq -r ".[$i].decision // \"\"" 2>/dev/null) || d=""
				r=$(printf '%s' "$decisions_json" | jq -r ".[$i].reason // \"\"" 2>/dev/null) || r=""
				alts=$(printf '%s' "$decisions_json" | jq -r ".[$i].alternatives // [] | .[]" 2>/dev/null) || alts=""
				[[ -z "$d" ]] && continue
				printf '- **%s** — %s\n' "$d" "$r"
				if [[ -n "$alts" ]]; then
					printf '  - *Considered:* '
					local first=1
					while IFS= read -r alt; do
						[[ -z "$alt" ]] && continue
						[[ "$first" -eq 0 ]] && printf ', '
						printf '%s' "$alt"
						first=0
					done <<< "$alts"
					printf '\n'
				fi
			done
			printf '\n'
		else
			printf '*None noted.*\n\n'
		fi

		printf '## Tradeoffs\n\n'
		local tradeoff_count
		tradeoff_count=$(printf '%s' "$tradeoffs_json" | jq 'length' 2>/dev/null) || tradeoff_count=0
		if [[ "$tradeoff_count" -gt 0 ]]; then
			printf '%s' "$tradeoffs_json" | jq -r '.[]' 2>/dev/null | while IFS= read -r item; do
				[[ -n "$item" ]] && printf '- %s\n' "$item"
			done
			printf '\n'
		else
			printf '*None noted.*\n\n'
		fi

		printf '## Constraints\n\n'
		local constraint_count
		constraint_count=$(printf '%s' "$constraints_json" | jq 'length' 2>/dev/null) || constraint_count=0
		if [[ "$constraint_count" -gt 0 ]]; then
			printf '%s' "$constraints_json" | jq -r '.[]' 2>/dev/null | while IFS= read -r item; do
				[[ -n "$item" ]] && printf '- %s\n' "$item"
			done
			printf '\n'
		else
			printf '*None noted.*\n\n'
		fi

		printf '## Out of Scope\n\n'
		local oos_count
		oos_count=$(printf '%s' "$out_of_scope_json" | jq 'length' 2>/dev/null) || oos_count=0
		if [[ "$oos_count" -gt 0 ]]; then
			printf '%s' "$out_of_scope_json" | jq -r '.[]' 2>/dev/null | while IFS= read -r item; do
				[[ -n "$item" ]] && printf '- %s\n' "$item"
			done
			printf '\n'
		else
			printf '*None noted.*\n\n'
		fi

		if [[ -n "$captured_prompt" ]]; then
			printf '## Initial Prompt\n\n'
			printf '```\n%s\n```\n\n' "$captured_prompt"
		fi

		printf '---\n'
		printf '*Generated by scribe · session `%s` · %s*\n' "$session_short" "$timestamp"
		[[ -n "$project_root" ]] && printf '*Project: `%s`*\n' "$project_root"
	}
}

scribe_distill() {
	local session_id="${1:-}"
	local cwd="${2:-}"
	local transcript_path="${3:-}"

	[[ -z "$session_id" ]] && return 1

	local onlooker_dir="${ONLOOKER_DIR:-${HOME}/.onlooker}"
	local state_file="${onlooker_dir}/scribe/sessions/${session_id}.json"

	# Load captured prompt from session state (best-effort).
	local captured_prompt=""
	if [[ -f "$state_file" ]]; then
		captured_prompt=$(jq -r '.captured_prompt // ""' "$state_file" 2>/dev/null) || captured_prompt=""
	fi

	# Transcript is required for extraction.
	if [[ -z "$transcript_path" || ! -f "$transcript_path" ]]; then
		printf 'scribe_distill: no transcript available for session %s\n' "$session_id" >&2
		return 1
	fi

	# Count turns; skip trivial sessions.
	local min_turns
	min_turns=$(scribe_config_get '.scribe.capture.min_turns') || min_turns="3"
	[[ -z "$min_turns" || "$min_turns" == "null" ]] && min_turns="3"

	local turn_count
	turn_count=$(scribe_count_turns "$transcript_path")

	if [[ "$turn_count" -lt "$min_turns" ]]; then
		return 2
	fi

	# Resolve config.
	local model timeout_s max_tokens temperature transcript_chars_max
	model=$(scribe_config_get '.scribe.evaluator.model')
	[[ -z "$model" || "$model" == "null" ]] && model="claude-haiku-4-5-20251001"
	timeout_s=$(scribe_config_get '.scribe.evaluator.timeout')
	[[ -z "$timeout_s" || "$timeout_s" == "null" ]] && timeout_s="60"
	max_tokens=$(scribe_config_get '.scribe.evaluator.max_tokens')
	[[ -z "$max_tokens" || "$max_tokens" == "null" ]] && max_tokens="2048"
	temperature=$(scribe_config_get '.scribe.evaluator.temperature')
	[[ -z "$temperature" || "$temperature" == "null" ]] && temperature="0.3"
	transcript_chars_max=$(scribe_config_get '.scribe.capture.transcript_chars_max')
	[[ -z "$transcript_chars_max" || "$transcript_chars_max" == "null" ]] && transcript_chars_max="40000"

	# Run extraction.
	local intent_json
	intent_json=$(scribe_extract_intent \
		"$transcript_path" "$model" "$timeout_s" "$max_tokens" "$temperature" "$transcript_chars_max") || {
		printf 'scribe_distill: extraction failed for session %s\n' "$session_id" >&2
		return 1
	}

	# Resolve project key and output paths.
	local project_key project_root output_dir
	project_key=$(scribe_project_key "$cwd")
	project_root=$(scribe_project_repo_root "$cwd")

	if [[ -n "$project_key" ]]; then
		output_dir=$(scribe_project_dir "$project_key")
	else
		output_dir="${onlooker_dir}/scribe/unknown"
	fi

	mkdir -p "$output_dir" 2>/dev/null || {
		printf 'scribe_distill: cannot create output dir %s\n' "$output_dir" >&2
		return 1
	}

	local date_str
	date_str=$(date '+%Y-%m-%d' 2>/dev/null) || date_str="unknown"
	local session_short="${session_id:0:8}"
	local filename="${date_str}-${session_short}.md"
	local output_path="${output_dir}/${filename}"

	# Format and write the document.
	local doc
	doc=$(_scribe_format_document \
		"$intent_json" "$session_id" "$project_root" "$captured_prompt")

	printf '%s\n' "$doc" > "$output_path" 2>/dev/null || {
		printf 'scribe_distill: failed to write %s\n' "$output_path" >&2
		return 1
	}

	# Mirror to project tree if configured.
	local mirror artifacts=1
	mirror=$(scribe_config_get '.scribe.output.mirror_to_project')
	if [[ "$mirror" == "true" && -n "$project_root" ]]; then
		local project_dir
		project_dir=$(scribe_config_get '.scribe.output.project_dir')
		[[ -z "$project_dir" || "$project_dir" == "null" ]] && project_dir="docs/decisions"
		local mirror_dir="${project_root}/${project_dir}"
		if mkdir -p "$mirror_dir" 2>/dev/null; then
			if cp "$output_path" "${mirror_dir}/${filename}" 2>/dev/null; then
				artifacts=2
			fi
		fi
	fi

	# Emit scribe.distill.complete.
	local payload
	payload=$(jq -n \
		--arg sid "$session_id" \
		--argjson cap 1 \
		--argjson art "$artifacts" \
		'{session_id: $sid, captures_processed: $cap, artifacts_produced: $art}') || payload=""

	[[ -n "$payload" ]] && scribe_emit_event "scribe.distill.complete" "$payload" || true

	printf '%s' "$output_path"
}
